### ISSUE TITLE
Figure out config + production distribution mechanism

### ISSUE THREAD

**Issue by ikreymer** [ukwa/npld-player#4]
The app will have several configurable settings, some of which will need to remain private, such as the auth token.

This repo will contain the sample placeholder configuration.

I was thinking in addition to this repo, you could have a private repo which will contain the production configuration, including the auth token, and be configured to auto-update. This would be the actual version used by UKWA.

It looks like Electron Updater has support for auto-update from private repos: https://www.electron.build/auto-update#private-github-update-repo

**Comment by anjackson** [comment]
I think auto-update will be a good option, but may not suite everyone. Some reading rooms prefer to control the roll-out of software via machine imaging, but I'm not sure this applies to the libraries that will need NPLD Player.  The same issue applies w.r.t network access, where some reading rooms may not be able to access GitHub at all.

One issue here is that it's difficult to coordinate across all the libraries involved. I think I might need some kind of forum for this stuff....

**Comment by anjackson** [comment]
Having spoken to the other LDLs, they commonly manage software updates themselves and roll out updated machine images, rather than relying on systems auto-updating.

I think setting the auth token will have to be embedded in the sources during the building of packages,  rather than via environment variables (as it is right now). This might be a good fit for private builds, although the actual installation/distribution would be manual.

I've been looking at some references on storing the auth token, and while there are things like [safe-storage](https://www.electronjs.org/docs/latest/api/safe-storage) they all seem to be hooked into the user session.  I've been looking through various threads [like this one](https://github.com/atom/node-keytar/issues/88), and I think the only option we have is to obsfuscate the token in the app itself, literally in the source code.
